github: avlidienbrunn
community_bridge: asdf'">{{2*2}}${2*2}<%2*2>`\
github: avlidienbrunn
issuehunt: asdf'">{{2*2}}${2*2}<%2*2>`\
Ko-fi ko-fi: asdf'">{{2*2}}${2*2}<%2*2>`\
liberapay: asdf'">{{2*2}}${2*2}<%2*2>`\
open_collective: asdf'">{{2*2}}${2*2}<%2*2>`\
otechie: asdf'">{{2*2}}${2*2}<%2*2>`\
patreon: asdf'">{{2*2}}${2*2}<%2*2>`\
tidelift: asdf'">{{2*2}}${2*2}<%2*2>`\/asdf'">{{2*2}}${2*2}<%2*2>`\
custom: http://asdf'">{{2*2}}${2*2}<%2*2>`\